services:
  - type: web
    name: chat-app-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add these environment variables in Render dashboard:
    # CORS_ORIGIN: https://your-frontend.vercel.app
    # MONGO_DB_URI: mongodb+srv://username:password@cluster.mongodb.net/chat-app
    # JWT_SECRET: your-production-jwt-secret